version: '3.8'

services:
  pmem-browser-agent:
    image: python:3.11-slim
    container_name: pmem-browser-agent
    volumes:
      - /mnt/pmem0:/mnt/pmem0
      - ../agents/browser_agent.py:/app/agent.py
    environment:
      - SHARED_PATH=/mnt/pmem0
    command: >
      sh -c "
      pip install requests &&
      tail -f /dev/null
      "

  pmem-code-agent:
    image: python:3.11-slim
    container_name: pmem-code-agent
    volumes:
      - /mnt/pmem0:/mnt/pmem0
      - ../agents/code_agent.py:/app/agent.py
    environment:
      - SHARED_PATH=/mnt/pmem0
    command: >
      sh -c "
      pip install python-pptx &&
      tail -f /dev/null
      "
  pmem-terminal-agent:
    image: python:3.11-slim
    container_name: pmem-terminal-agent
    volumes:
      - /mnt/pmem0:/mnt/pmem0
      - ../agents/terminal_agent.py:/app/agent.py
    environment:
      - SHARED_PATH=/mnt/pmem0
    command: tail -f /dev/null